/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/arduino.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Arduino(props) {
  const { nodes, materials } = useGLTF('/models/arduino.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat5} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat16} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat12} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat15} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat22} />
    </group>
  )
}

useGLTF.preload('/models/arduino.glb')
