/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/models/Desk.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Desk(props) {
  const { nodes, materials } = useGLTF('/models/Desk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.desk.geometry} material={materials.wood} />
      <mesh geometry={nodes.desk_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.drawer_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.drawer_1_1.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/models/Desk.glb')
